public static class LogData
{
   public static readonly string[] Sentences =
   {
      "David proudly graduated from high school top of his class at age 97.",
      "Various sea birds are elegant, but nothing is as elegant as a gliding pelican.",
      "She can live her life however she wants as long as she listens to what I have to say.",
      "It's important to remember to be aware of rampaging grizzly bears.",
      "He had a vague sense that trees gave birth to dinosaurs.",
      "There was coal in his stocking and he was thrilled.",
      "She felt that chill that makes the hairs on the back of your neck when he walked into the room.",
      "Red is greener than purple, for sure.",
      "Never underestimate the willingness of the greedy to throw you under the bus.",
      "The delicious aroma from the kitchen was ruined by cigarette smoke.",
      "She had a difficult time owning up to her own crazy self.",
      "The beach was crowded with snow leopards.",
      "The team members were hard to tell apart since they all wore their hair in a ponytail.",
      "She folded her handkerchief neatly.",
      "As you consider all the possible ways to improve yourself and the world, you notice John Travolta seems fairly unhappy.",
      "Smoky the Bear secretly started the fires.",
      "He loved eating his bananas in hot dog buns.",
      "Pair your designer cowboy hat with scuba gear for a memorable occasion.",
      "He went back to the video to see what had been recorded and was shocked at what he saw.",
      "Joyce enjoyed eating pancakes with ketchup.",
      "He dreamed of eating green apples with worms.",
      "The stench from the feedlot permeated the car despite having the air conditioning on recycled air.",
      "For the 216th time, he said he would quit drinking soda after this last Coke.",
      "Patricia loves the sound of nails strongly pressed against the chalkboard.",
      "If you like tuna and tomato sauce - try combining the two. It’s really not as bad as it sounds.",
      "Normal activities took extraordinary amounts of concentration at the high altitude.",
      "The river stole the gods.",
      "He uses onomatopoeia as a weapon of mental destruction.",
      "You've been eyeing me all day and waiting for your move like a lion stalking a gazelle in a savannah.",
      "He wondered if she would appreciate his toenail collection.",
      "I was offended by the suggestion that my baby brother was a jewel thief.",
      "The mysterious diary records the voice.",
      "She was disgusted he couldn’t tell the difference between lemonade and limeade.",
      "You'll see the rainbow bridge after it rains cats and dogs.",
      "She lived on Monkey Jungle Road and that seemed to explain all of her strangeness.",
      "The beauty of the African sunset disguised the danger lurking nearby.",
      "A dead duck doesn't fly backward.",
      "He found a leprechaun in his walnut shell.",
      "He set out for a short walk, but now all he could see were mangroves and water were for miles.",
      "She was the type of girl who wanted to live in a pink house.",
      "He shaved the peach to prove a point.",
      "She couldn't understand why nobody else could see that the sky is full of cotton candy.",
      "I've always wanted to go to Tajikistan, but my cat would miss me.",
      "The tart lemonade quenched her thirst, but not her longing.",
      "The crowd yells and screams for more memes.",
      "I like to leave work after my eight-hour tea-break.",
      "A quiet house is nice until you are ordered to stay in it for months.",
      "The pet shop stocks everything you need to keep your anaconda happy.",
      "The sign said there was road work ahead so he decided to speed up.",
      "It's much more difficult to play tennis with a bowling ball than it is to bowl with a tennis ball.",
      "She wondered what his eyes were saying beneath his mirrored sunglasses.",
      "The family’s excitement over going to Disneyland was crazier than she anticipated.",
      "Not all people who wander are lost.",
      "He went back to the video to see what had been recorded and was shocked at what he saw.",
      "Now I need to ponder my existence and ask myself if I'm truly real.",
      "Bill ran from the giraffe toward the dolphin.",
      "I am happy to take your donation; any amount will be greatly appreciated.",
      "The rain pelted the windshield as the darkness engulfed us.",
      "His get rich quick scheme was to grow a cactus farm.",
      "The Japanese yen for commerce is still well-known.",
      "He had a wall full of masks so she could wear a different face every day.",
      "Mothers spend months of their lives waiting on their children.",
      "I covered my friend in baby oil.",
      "The ants enjoyed the barbecue more than the family.",
      "Buried deep in the snow, he hoped his batteries were fresh in his avalanche beacon.",
      "Check back tomorrow; I will see if the book has arrived.",
      "The tortoise jumped into the lake with dreams of becoming a sea turtle.",
      "The child’s favorite Christmas gift was the large box her father’s lawnmower came in.",
      "The delicious aroma from the kitchen was ruined by cigarette smoke."
   };

   public static readonly string[] Names =
   {
      "Jordan Trevino",
      "Gina Berry",
      "Jami Hampton",
      "Rhett Oconnor",
      "Tommie Reed",
      "Annie Duncan",
      "Kerri Hurst",
      "Dalton Mccullough",
      "Marlene Gentry",
      "Jae Watson",
      "Serena Vega",
      "Liza Lam",
      "Claude Archer",
      "Rocco Lamb",
      "Edison Parsons",
      "Gus Mosley",
      "Shelby Pierce",
      "Aaron Luna",
      "Randal Frost",
      "Phyllis Newton",
      "Della Booker",
      "Deshawn Mckinney",
      "Emmitt Rose",
      "Santiago Gill",
      "Elena Buck",
      "Rupert Osborn",
      "Henry Parks",
      "Kimberley Rich",
      "Rayford Lyons",
      "Raphael Obrien",
      "Erica Snyder",
      "Chrystal English",
      "Chelsea Sexton",
      "Jaclyn Chavez",
      "Christian Dickson",
      "Deena Mclaughlin",
      "Carey Aguirre",
      "Esteban Mack",
      "Hugh Kirby",
      "Chasity Shields",
      "Rosanne Koch",
      "Rob Johnston",
      "Stephanie Mcclure",
      "Booker Salas",
      "Ryan Moses",
      "Kirby Perry",
      "Harrison Holloway",
      "Hope Lucas",
      "Jeanie Rollins",
      "Marie Barrera",
      "Hiram Buttonwood",
      "Orie Olive",
      "Sol Cobweb",
      "Jimmie Griffin",
      "Rain Ash",
      "Denver Toads",
      "Cade Poults",
      "Florian Cobris",
      "Pembroke Colten",
      "Onyx Crooks",
      "Talon Cygnet",
      "Erwin Silverthorn",
      "Lennie Kettles",
      "Travis Willows",
      "Aubrey Ironbark",
      "Spruce Leon",
      "Hampton Dogwood",
      "Houston Griffins",
      "Wilton Box",
      "Heath Griffins",
      "Branch Boartusk",
      "Oakley Pugs",
      "Wong Hearth",
      "Dow Leveret",
      "Bronze Fiddlewood",
      "Lew Nettle",
      "Dusk Littletree",
      "Judge Arbutus",
      "Ellis Firewheel",
      "Aedan Biscus",
      "Leon Crabapple",
      "Aegis Slumber",
      "Jordan Newts",
      "Carnelian Sow",
      "Herschel Selket",
      "Brook Primrose",
      "Loy Mulberry",
      "Cotton Hinde",
      "Judas Bags",
      "Wellington Oleander",
      "Nicholas Fluke",
      "Lagoon Mandrake",
      "Reginald Sweaters",
      "Garfield Kettles",
      "Huntley Leveret",
      "Asher Strix",
      "Stormy Gooseberry",
      "Axel Mole",
      "Bud Barracus",
      "Thicket Bucks"
   };
}
